language: python
# command to install dependencies
cache: pip

matrix:
  include:
    - python: 3.6
      env:
        - MIN_REQUIREMENTS=1
    - python: 3.7
      env:
        - MIN_REQUIREMENTS=1
    - python: 3.6
    - python: 3.7

install:
  - if [[ "${MIN_REQUIREMENTS}" == "1" ]]; then
      python -c "req = open('requirements.txt').read().replace('>', '=') ; open('requirements-ci.txt', 'w').write(req)" ;
    else
      cp requirements.txt requirements-ci.txt ;
    fi
  - pip install Cython
  - pip install -r requirements-ci.txt

# keep build from timing out
dist: xenial  # Ubuntu 16.04

# command to run tests
script:
  - pip install -e .
  - pytest . -v # or py.test for Python versions 3.5 and below
