language: python
python:
  - "3.6"
# command to install dependencies
cache: pip
install:
  - pip install --progress-bar off -r requirements.txt
  - pip install --progress-bar off -e .

# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
